language: php

php:
  - 5.6
  - 7.0
  - 7.1

env:
  global:
    - setup=basic

before_script:
  - travis_retry composer self-update

install:
  - travis_retry composer install --no-interaction --prefer-dist

# cache vendors
cache:
  directories:
    - vendor
    - $HOME/.composer/cache  

script: vendor/bin/phpunit